POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "",
    "password": "",
    "lastname": "",
    "telephone":"",
    "email":""
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "@mail.com",
    "password": ""
}

###
GET http://localhost:3000/api/auth/
###
PUT http://localhost:3000/api/auth/jacinto@mail.com


###
POST http://localhost:3000/api/auth/geotab_login
Content-Type: application/json

{
    "username": "mail@.com",
    "password": "mailpass",
    "database": "dbname",
}

 
###
 GET http://localhost:3000/api/auth/confirmation/








###
POST http://35.209.128.105:3389/api/auth/register
Content-Type: application/json

{
    "username": "te5t",
    "password": "test123",
    "lastname": "testor",
    "telephone":"8883388888",
    "email":"noexiste3@yahoo.com"
}