POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "",
    "password": "",
    "lastname": "",
    "telephone":"",
    "email":""
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "jesus.valdez@metricamovil.com",
    "password": "pass123"
}

###
GET http://localhost:3000/api/auth/
###
PUT http://localhost:3000/api/auth/jacinto@mail.com


###
POST http://localhost:3000/api/auth/geotab_login
Content-Type: application/json

{
    "username": "mail@.com",
    "password": "mailpass",
    "database": "dbname",
}

 
###
 GET http://localhost:3000/api/auth/confirmation/








###
POST http://35.209.128.105:3389/api/auth/register
Content-Type: application/json

{
    "username": "ok1234",
    "password": "ok1234",
    "lastname": "testor",
    "telephone":"8883188888",
    "email":"ok1234@yahoo.com"
}


###
POST http://35.209.128.105:3389/api/auth/login
Content-Type: application/json

{
    "email": "ok1234@yahoo.com",
    "password": "ok1234"
}